version: '3.9'
services:
  kitchen-service:
    build:
        context: ./KitchenService
        dockerfile: Dockerfile
    container_name: KitchenService
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=sql_database_2022;Database=KitchenService;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true
        - RABBIT_MQ_SERVER=rabbit_mq
        - RABBIT_MQ_USERNAME=guest
        - RABBIT_MQ_PASSWORD=guest
        - RABBITMQSETTINGS__EXCHANGENAME=OfferExchange
        - RABBITMQSETTINGS__EXCHHANGETYPE=direct
        - RABBITMQSETTINGS__QUEUENAME=offer_queue
        - RABBITMQSETTINGS__ROUTEKEY=offer_route
    ports:
        - "4201:80"    
  order-service:
    build:
        context: ./OrderService
        dockerfile: Dockerfile
    container_name: OrderService
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=sql_database_2022;Database=OrderService;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true
        - RABBIT_MQ_SERVER=rabbit_mq
        - RABBIT_MQ_USERNAME=guest
        - RABBIT_MQ_PASSWORD=guest
        - RABBITMQSETTINGS__EXCHANGENAME=OfferExchange
        - RABBITMQSETTINGS__EXCHHANGETYPE=direct
        - RABBITMQSETTINGS__QUEUENAME=offer_queue
        - RABBITMQSETTINGS__ROUTEKEY=offer_route
    ports:
        - "4202:80"    
  payment-service:
    build:
        context: ./PaymentService
        dockerfile: Dockerfile
    container_name: PaymentService
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=sql_database_2022;Database=PaymentService;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true
        - RABBIT_MQ_SERVER=rabbit_mq
        - RABBIT_MQ_USERNAME=guest
        - RABBIT_MQ_PASSWORD=guest
        - RABBITMQSETTINGS__EXCHANGENAME=OfferExchange
        - RABBITMQSETTINGS__EXCHHANGETYPE=direct
        - RABBITMQSETTINGS__QUEUENAME=offer_queue
        - RABBITMQSETTINGS__ROUTEKEY=offer_route
    ports:
        - "4203:80"    
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver_database_2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672